apiVersion: v1
kind: Service
metadata:
  name: ping-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    component: ping
  ports:
    - protocol: "TCP" 
      port: 8080
      targetPort: 8080
