apiVersion: v1
kind: Service
metadata:
  name: user-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    component: user
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
